# ================= DATABASE =================

# Use PostgreSQL if env vars exist, otherwise fallback to H2 (local)
spring.datasource.url=${DB_URL:jdbc:h2:mem:testdb}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:}

# Driver (auto-switch based on DB)
spring.datasource.driver-class-name=${DB_DRIVER:org.h2.Driver}

# JPA
spring.jpa.database-platform=${DB_PLATFORM:org.hibernate.dialect.H2Dialect}
spring.jpa.hibernate.ddl-auto=update

# ================= SERVER =================
server.port=${PORT:8080}
server.address=0.0.0.0

spring.main.web-application-type=servlet

# ================= EMAIL =================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true